
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async errorPopup(msg: string) : Promise<void> {
    await TAURI_INVOKE("error_popup", { msg });
},
async loadLibrary(libraryJson: string) : Promise<Result<LibraryTauri, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_library", { libraryJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFilePersistentAndroid() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file_persistent_android") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrackByItemId(itemId: number) : Promise<Result<Track, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_track_by_item_id", { itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTracksPage(options: TracksPageOptions) : Promise<Result<TracksPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tracks_page", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CountObject = { count: string; fromDate: string; toDate: string }
export type Field = "Title" | "Artist" | "Album" | "AlbumArtist" | "Comments" | "Genre" | "Composer" | "Group" | "Year" | "Plays" | "Skips" | "Bpm"
export type FilterTerm = { field: Field | null; literal: string }
export type Folder = { id: string; name: string; description?: string | null; liked: boolean; disliked: boolean; 
/**
 * For example "itunes"
 */
importedFrom?: string | null; 
/**
 * For example iTunes Persistent ID
 */
originalId?: string | null; dateImported?: string | null; dateCreated?: string | null; children: string[] }
export type LibraryTauri = { track_lists: Partial<{ [key in string]: TrackList }>; song_count: string }
export type Playlist = { id: string; name: string; description?: string | null; liked: boolean; disliked: boolean; importedFrom?: string | null; originalId?: string | null; dateImported?: string | null; dateCreated?: string | null; tracks: number[] }
export type Special = { id: string; name: SpecialTrackListName; dateCreated: string; children: string[] }
export type SpecialTrackListName = "Root"
export type Track = { 
/**
 * id
 */
i: number; 
/**
 * size
 */
z: string; 
/**
 * duration
 */
d: number; 
/**
 * bitrate
 */
br: number; 
/**
 * sampleRate
 */
sr: number; 
/**
 * file
 */
f: string; 
/**
 * dateModified
 */
dm: string; 
/**
 * dateAdded
 */
da: string; 
/**
 * name
 */
t: string; 
/**
 * importedFrom
 */
if?: string | null; 
/**
 * originalId, Imported ID, like iTunes Persistent ID
 */
oi?: string | null; 
/**
 * artist
 */
a?: string; 
/**
 * composer
 */
c?: string | null; 
/**
 * sortName
 */
st?: string | null; 
/**
 * sortArtist
 */
sa?: string | null; 
/**
 * sortComposer
 */
sc?: string | null; 
/**
 * genre
 */
g?: string | null; 
/**
 * rating
 */
r?: number | null; 
/**
 * year
 */
y?: string | null; 
/**
 * bpm
 */
b?: number | null; 
/**
 * comments
 */
n?: string | null; 
/**
 * grouping
 */
gr?: string | null; 
/**
 * liked
 */
l?: boolean | null; 
/**
 * disliked
 */
dl?: boolean | null; 
/**
 * disabled
 */
db?: boolean | null; 
/**
 * compilation
 */
cp?: boolean | null; 
/**
 * albumName
 */
at?: string | null; 
/**
 * albumArtist
 */
aa?: string | null; 
/**
 * sortAlbumName
 */
sat?: string | null; 
/**
 * sortAlbumArtist
 */
saa?: string | null; 
/**
 * trackNum
 */
tn?: number | null; 
/**
 * trackCount
 */
tc?: number | null; 
/**
 * discNum
 */
dn?: number | null; 
/**
 * discCount
 */
dc?: number | null; 
/**
 * dateImported
 */
di?: string | null; 
/**
 * playCount
 */
pn?: number | null; 
/**
 * plays
 */
p?: string[] | null; 
/**
 * playsImported
 */
pi?: CountObject[] | null; 
/**
 * skipCount
 */
sn?: number | null; 
/**
 * skips
 */
s?: string[] | null; 
/**
 * skipsImported
 */
si?: CountObject[] | null; 
/**
 * volume, -100 to 100
 */
v?: number | null }
export type TrackList = ({ type: "playlist" } & Playlist) | ({ type: "folder" } & Folder) | ({ type: "special" } & Special)
export type TracksPage = { playlist_kind: string; playlist_name: string; playlist_description: string | null; playlist_length: number; item_ids: number[] }
export type TracksPageOptions = { playlist_id: string; sort_key: string; sort_desc: boolean; filter_terms: FilterTerm[]; group_album_tracks: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
